# Generated by Django 6.0.7 on 2026-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbbs_certificate',
            field=models.FileField(blank=True, null=True, upload_to='mbbs_certificates/'),
        ),
    ]
