# Generated by Django 6.0.7 on 2026-07-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='recordsharerequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='recordsharerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='patients.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name')},
        ),
    ]
