# Generated by Django 6.0.7 on 2026-07-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
