# Generated by Django 6.0.7 on 2026-07-08 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bio', models.TextField(blank=True)),
                ('is_emergency_authorized', models.BooleanField(default=False, help_text='Can this doctor use one-click emergency access mode?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
